export const ProductGridApi = [
  {
    id: 1,
    Img: "assets/images/product/product-1.jpg",
    Font: "star",
    Review: "4.5 \n (145)",
    TopHeading: "Oculus VR",
    Heading: "Reference 1204",
    Price: "$ 149",
    PageNo: "Previous",
  },
  {
    id: 2,
    Img: "assets/images/product/product-1.jpg",
    Font: "star",
    Review: "4.5 \n (145)",
    TopHeading: "Oculus VR",
    Heading: "Reference 1204",
    Price: "$ 149",
    PageNo: "1",
  },
  {
    id: 3,
    Img: "assets/images/product/product-1.jpg",
    Font: "star",
    Review: "4.5 \n (145)",
    TopHeading: "Oculus VR",
    Heading: "Reference 1204",
    Price: "$ 149",
    PageNo: "2",
  },
  {
    id: 4,
    Img: "assets/images/product/product-1.jpg",
    Font: "star",
    Review: "4.5 \n (145)",
    TopHeading: "Oculus VR",
    Heading: "Reference 1204",
    Price: "$ 149",
    PageNo: "3",
  },
  {
    id: 5,
    Img: "assets/images/product/product-1.jpg",
    Font: "star",
    Review: "4.5 \n (145)",
    TopHeading: "Oculus VR",
    Heading: "Reference 1204",
    Price: "$ 149",
    PageNo: "Next",
  },
];
