export const ProductListApi = [
  {
    id: "1",
    Img: "assets/images/product/product-2.jpg",
    TopHeading: "Oculus VR",
    Heading: "Reference 1204",
    Time: "20h:46m:30s",
    Text: "Offer",
    Text1: "Bank Offer",
    Price: "Price",
    Doller: "$399",
    Rating: "Ratings",
    Font: "star",
    RatingCount: "3.5",
    Count: "(77)",
    PageNo: "Previous",
  },
  {
    id: "2",
    Img: "assets/images/product/product-2.jpg",
    TopHeading: "Oculus VR",
    Heading: "Reference 1204",
    Time: "20h:46m:30s",
    Text: "Offer",
    Text1: "Bank Offer",
    Price: "Price",
    Doller: "$399",
    Rating: "Ratings",
    Font: "star",
    RatingCount: "3.5",
    Count: "(77)",
    PageNo: "1",
  },
  {
    id: "3",
    Img: "assets/images/product/product-2.jpg",
    TopHeading: "Oculus VR",
    Heading: "Reference 1204",
    Time: "20h:46m:30s",
    Text: "Offer",
    Text1: "Bank Offer",
    Price: "Price",
    Doller: "$399",
    Rating: "Ratings",
    Font: "star",
    RatingCount: "3.5",
    Count: "(77)",
    PageNo: "3",
  },
  {
    id: "4",
    Img: "assets/images/product/product-2.jpg",
    TopHeading: "Oculus VR",
    Heading: "Reference 1204",
    Time: "20h:46m:30s",
    Text: "Offer",
    Text1: "Bank Offer",
    Price: "Price",
    Doller: "$399",
    Rating: "Ratings",
    Font: "star",
    RatingCount: "3.5",
    Count: "(77)",
    PageNo: "Next",
  },
];
